name: mess
version: '0.1.0.0'
category: Web
author: Author name here
maintainer: example@example.com
copyright: 2017 Author name here
license: BSD3
homepage: https://github.com/githubuser/mess#readme
extra-source-files:
- README.md
dependencies:
- base >=4.7 && <5
- text >=1.2 && <2
- unix-time >=0.3 && <1
- aeson >=1.1 && <2
- aeson-pretty >=0.8 && <1
- bytestring >=0.10 && <1
- binary >=0.8 && <1
- optparse-applicative >=0.13 && <1
- blaze-html >=0.9 && <1
- blaze-markup >=0.8 && <1
- file-embed >=0.0 && <1
- containers >=0.5 && <1
- generic-deriving >=1.12 && <2
- wreq >=0.5.2 && <1
- lens >=4.15 && <5
- network-uri >=2.6 && <3
- SafeSemaphore >=0.10 && <1
- filepath >=1.4 && <2
- directory >=1.3 && <2
- ascii-progress >=0.3 && <1
- data-default >=0.7 && < 1
- async >=2.1 && <3
- VKHS
ghc-options:
- -Wall
library:
  source-dirs: src
  exposed-modules:
  - Data.VkMess
  - App.Fetch
  - Text.Html.VkMess
  - Text.Html.VkMess.Static
executables:
  mess-html:
    main: Main.hs
    source-dirs: app/html/
    dependencies: mess
  mess-fetch:
    main: Main.hs
    source-dirs: app/fetch/
    dependencies: mess
  mess-cache:
    ghc-options:
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: app/cache/
    dependencies: mess
